// authentication
export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const RESET_REGISTER_INITIALSTATE = "RESET_REGISTER_INITIALSTATE";

// places
export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_ERROR = "PLACES_ERROR";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const UPDATE_PLACES_SUCCESS = "UPDATE_PLACES_SUCCESS";

// user favourites
export const FAVORITE_REQUEST = "FAVORITE_REQUEST";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";

// reset
export const RESET_FAVORITE_INITIALSTATE = "RESET_FAVORITE_INITIALSTATE";
